sonic-net/sonic-wpa-supplicant

Makefile.am
Removed -lsonic_cps_class_map from libsonic_nas_qos_la_LIBADD.
=> Fix overlinking

debian/patches/series, lgtm.yml
Remove a patch for WPA_GUI in debian and add dependencies in lgtm.yml
This patch is for hostap_2_9, but it's not compatible with the master branch.
=> [Fix LGTM]: Remove conflicted WAP_GUI patch

src/pae/ieee802_1x_kay.c
Changed format specifiers from %lu to %" PRIu64 " to avoid compilation errors
in arm 32-bit
=> [build] Fix build error when compiling for armhf (32-bit)

src/drivers/driver_macsec_sonic.c
It's clearer to rename the init_pn to next_pn.
We have a commit(https://github.com/Azure/sonic-wpa-supplicant/commit/e77db616ff9d7675d354b29791aa6b6e21227c11) to rename all init_pn to next_pn. But it forgot to modify the name in `macsec_sonic_set_transmit_next_pn`. This PR is for fixing this mistake.
=> Fix missing refactor

src/drivers/driver_macsec_sonic.c
This PR is for fixing the wrong key of SA.
There is a wrong comma in `CREATE_SA_KEY` which cuts the format string. The expected key of SA should like `Ethernet0:72203427286897918:0`, but the wrong format will cause that it like `::%u:72203427286897918:0`
=> Fixbug: wrong SA key

src/pae/ieee802_1x_cp.c
This PR is to fix issues with CP state machine found during testing AN rollover.
It was seen that when MACsec live peer timeout coincides with AN rollover on Key server, there can be two valid state machine transitions from CP Receiving state:  Abandon and Transmit.  This results in both Abandon and Transmit handling being executed by CP state machine, Key server will remain stuck in invalid Transmit state, and CP state machine will not recover without manual intervention.
Changes update CP state machine so that multiple transition paths cannot be executed from any given CP state.
=> Fix for CP state machine issues

src/drivers/driver_macsec_sonic.c
What I did
Updated wpa-supplicant macsec_sonic driver to program XPN information in APPL_DB.
Why I did it
MACsec XPN support.
How I verified it
System tests on Juniper platform which supports MACsec XPN.
Details if related
N/A
=> MACsec XPN changes

src/drivers/driver_macsec_sonic.c
**What I did**
Support was previously added for "macsec_include_sci" attribute in wpasupplicant configuration profile, but this support was not extended to macsec_sonic driver and SONiC APPL_DB.  I have added the needed support in the macsec_sonic driver to allow the "send_sci" APPL_DB attribute to be configured by "macsec_include_sci" wpasupplicant attribute.
**Why I did it**
Missing support in wpasupplicant macsec_sonic driver for send_sci APPL_DB attribute.
**How I verified it**
System test with VS and JNPR platforms.
**Details if related**
N/A
=> [macsec_sonic] driver support for macsec_include_sci

src/ap/wpa_auth_kay.c, src/pae/ieee802_1x_kay.c, src/pae/ieee802_1x_kay.h, wpa_supplicant/config.c, wpa_supplicant/config_file.c, wpa_supplicant/config_ssid.h, wpa_supplicant/wpa_cli.c, wpa_supplicant/wpas_kay.c
Add a new configuration instruction `macsec_rekey_period` to indicate the period of proactively refresh SAK.
e.g. `macsec_rekey_period=1800`, which means the macsec SA will be refreshed proactively every 1800 seconds.
=> Proactively rekey

src/drivers/sonic_operators.cpp
We found that the time needed for enabling macsec may be longer than the old timeout, which make the operation failed unexpectedly.
=> Increase select timeout

debian/config/wpasupplicant/linux
Due to P2P module has vulnerability and it wasn't used in SONiC project, disable it.
* CVE-2021-27803
A vulnerability was discovered in how p2p/p2p_pd.c in wpa_supplicant before 2.10 processes P2P (Wi-Fi Direct) provision discovery requests. It could result in denial of service or other impact (potentially execution of arbitrary code), for an attacker within radio range.
* CVE-2021-0326
In p2p_copy_client_info of p2p.c, there is a possible out of bounds write due to a missing bounds check. This could lead to remote code execution if the target device is performing a Wi-Fi Direct search, with no additional execution privileges needed. User interaction is not needed for exploitation.Product: AndroidVersions: Android-10 Android-11 Android-8.1 Android-9Android ID: A-172937525
Signed-off-by: …
=> Disable P2P module due to vulnerability

src/drivers/driver_macsec_linux.c
Cannot dump the correct PN from Linux Kernel due to the PN type error.
=> [macsec_linux]: Fixbug cannot dump the PN due to type error

debian/rules
According to the patch for bullseye from: https://packages.debian.org/bullseye/wpasupplicant, to disable the warning: array-bounds
=> [debian]: Disable warning: array-bounds

wpa_supplicant/driver_i.h
To enable MACsec Linux driver, but `macsec_get_max_sa_per_sc` isn't implemented to linux driver so that the MKA session cannot been created.
https://github.com/Azure/sonic-wpa-supplicant/blob/447e9f708df996b8de88ce4fe703c0901357e12b/src/pae/ieee802_1x_kay.c#L3662-L3665
The hierarchy is `secy_get_max_sa_per_sc`->`wpa_drv_macsec_get_max_sa_per_sc`->`wpa_driver_ops::macsec_get_max_sa_per_sc`
=> [macsec_linux]: Fix compatibility of macsec_get_max_sa_per_sc to macsec linux

src/drivers/sonic_operators.cpp
Fix issue: https://github.com/Azure/sonic-wpa-supplicant/issues/53
Wait operator doesn't compare key so that it will return success with a false positive.
=> [sonic_operators.cpp]: Fixbug wait with  false positive to return success

src/drivers/sonic_operators.cpp, src/drivers/sonic_operators.h
Re-implment `get_counter` with `swss::CounterTable`, which is ok to get macsec counter w/o gearbox.
=> [sonic_operators.cpp] Update sonic_db_manager::get_counter

src/drivers/sonic_operators.cpp
According to syslog, the first MACsec events may be processed by orchagent after 5mins in config reload stage. So, increasing the select timeout avoids the exiting of mka state machine.
=> [sonic_operators.cpp]: Increasing select timeout

src/pae/ieee802_1x_kay.c, src/pae/ieee802_1x_kay_i.h
1. Fix rekey of PN based cannot triggered in XPN cipher due to the wrong type of lpn with u32.
2. Ignore type 8 (MKA_XPN ) of MKA frame 
=> [mka]: Fix rekey of PN based cannot triggered in XPN cipher

src/drivers/driver_macsec_sonic.c
If the Ingress or Egress SA hasn't been enabled, the related entry in state db would not be created. So, We shouldn't wait for state db if to delete an un-enabled SA. Otherwise the db_wait will trigger a timeout issue.
=> [driver_macsec_sonic.c]: Fixbug: a wrong db_wait in delete sa

src/utils/eloop.c
Increase the timeout of signal termination from 2 seconds to 120 seconds. Because the cleanup MACsec objs depends on the response from orchagent, but the orchagent cannot always handle all cleanup actions within 2 seconds. So increase this timeout to guarantee all MACsec objs can be cleanup successfully.
=> [eloop.c]: Increase timeout of signal termination

src/pae/ieee802_1x_kay.c
Key server may be removed due to the ingress packets delay. In this situation, the endpoint of key server may not be aware of this participant who has removed the key server from the peer list. Because the egress traffic is normal, the key server will not remove this participant from the peer list of key server. So in the next MKA message, the key server will not dispatch a new SAK to this participant.
And this participant can not be aware that is a new round of communication so it will not update its mi at re-adding the key server to its peer list.
So we need to update mi to avoid the failure of the re-establishment MKA session.
The following is the issue situation log that failed to re-establish after a cleanup. It shows the wpa_supplicant continuously processes two ingress packets so …
=> [mka]: Fix re-establishment by reset MI

src/pae/ieee802_1x_kay.c
Because the key server may not include dist sak and use sak in ONE packet, Meanwhile, after dist sak, the current participant(Non-Key Server) will install SC or SA(s) after decoding the dist sak which may take few seconds in real physical platforms. Meanwhile, the peer expire time is always initialized at adding the key server to peer list. The gap between adding the key server to peer list and processing next use sak packet may exceed the threshold of MKA_LIFE_TIME(6s). It will cause an unexpected cleanup (delete SC and SA(s)). So, update the expire timeout at dist sak also.
The following are debug logs from wpa_supplicant at the issue time slot.
```python
Apr 18 00:15:58.283482 DEBUG macsec0#wpa_supplicant[18]: KaY: Decode received MKPDU (ifname=Ethernet0)
Apr 18 00:15:58.283533 DEBUG …
```
=> [mka]: Fix unexpected cleanup

src/crypto/crypto_openssl.c
Replace wpa-supplicant openssl CMAC wrapper API to use high level EVP APIs. With this change CMAC handlings for openssl will be taken over by symcrypt provider in FIPs mode. 
Test: Tested against whole macsec testing suites and all passed with the change. 
This is porting from hostap wpa_supplicant for CMAC Openssl hihe level API replacement. 
https://w1.fi/cgit/hostap/commit/?id=0c61f6234fd27c43b46d9bdb8ecf72be2e85cc38
=> Provide CMAC high level API replacement

hostapd/Makefile, src/crypto/crypto_openssl.c, wpa_supplicant/Makefile
Wpa_supplicant OpenSSL CMAC wrapper API (omac1_aes_vector) is only available when FIPs is enabled for build. Which should not be the case. Openssl CMAC wrapper API should also be available under non FIPS mode. When wpa-supplicant is referencing to use openssl,  openssl CMAC should be triggered instead of wpa internal one.
The fix is mostly taking from hostap with those changes already:
https://w1.fi/cgit/hostap/commit/src/crypto?id=ae0f6ee97ed4924189f2cd68548d2a971f17d67e https://w1.fi/cgit/hostap/commit/wpa_supplicant/Makefile?id=ae0f6ee97ed4924189f2cd68548d2a971f17d67e
Testing has been done with the changes with FIPS and non FIPS mode by running sonic macsec testing suite. It's observed in all scenario openssl CMAC API is triggered.
=> Make Openssl CMAC API (omac1_aes_vector) Availalable in Non FIPs Mode

hostapd/ctrl_iface.c, src/ap/ieee802_1x.c, src/eap_server/eap.h, src/eap_server/eap_server.c, src/eapol_auth/eapol_auth_sm.c, src/eapol_auth/eapol_auth_sm.h, src/eapol_auth/eapol_auth_sm_i.h, src/utils/wpa_debug.c
#Why I did it
These changes are done to support the interaction between PAC and the 8021.X which is in sonic-wpasupplicant.
#How I did it
#How to verify it
=> Changes to support PAC and 802.1X interaction
